apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: equivalent-armadillo-java-springboot
  janus-idp.io/tekton: equivalent-armadillo-java-springboot
  backstage.io/kubernetes-id: equivalent-armadillo-java-springboot
  backstage.io/kubernetes-namespace: rhtap-e2e-ci 
  app.kubernetes.io/part-of: equivalent-armadillo-java-springboot
resources: 
- deployment.yaml
- route.yaml
- service.yaml
